package src;

/*Generated by MPS */

import java.io.File;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileInputStream;
import java.io.FileOutputStream;

public class Main {
  public static int countoccurences(String word, File file) {
    BufferedReader reader;
    int count = 0;
    try {
      reader = new BufferedReader(new FileReader(file));
      String line = reader.readLine();
      while (line != null) {
        String[] words = line.split(" ");
        for (int i = 0; i < words.length; i++) {
          if (word.toLowerCase().equals(words[i].toLowerCase())) {
            count = count + 1;
          }
        }
        line = reader.readLine();
      }
      reader.close();
    } catch (IOException e) {
    }
    return count;
  }
  public static int rank(String searchquery, File file) {
    int termfrequency = 0;
    String[] queryterms = searchquery.split(" ");
    for (int loop = 0; loop < queryterms.length; loop++) {
      termfrequency = termfrequency + countoccurences(queryterms[loop], file);
    }

    return termfrequency;
  }

  public static boolean deleteDocument(File file) {
    if (file.delete()) {
      System.out.println("Document Deleted Successfully");
      return true;
    }
    System.out.println("Document not found");
    return false;
  }

  public static boolean addDocument(File file) throws IOException {
    String whereami = System.getProperty("user.dir");
    System.out.println(whereami);
    File folder = new File(whereami + "\\" + "documents" + "\\");
    File[] listoffiles = folder.listFiles();
    System.out.println("listoffiles length is " + listoffiles.length);
    for (int i = 1; i <= listoffiles.length; i++) {
      File filetrav = new File(whereami + "\\documents" + "\\" + "file" + i + ".txt");
      if (!(filetrav.exists())) {
        try {
          filetrav.createNewFile();
          System.out.println("New document with file name : file" + i + ".txt created");
          FileInputStream input = new FileInputStream(file);
          FileOutputStream output = new FileOutputStream(filetrav);
          byte[] buffer = new byte[1024];
          int n;
          while ((n = input.read(buffer)) != -1) {
            output.write(buffer, 0, n);
          }
          input.close();
          output.close();
          return true;
        } catch (IOException e) {
        }
      }
    }
    File filetrav = new File(whereami + "\\documents" + "\\" + "file" + (listoffiles.length + 1) + ".txt");
    try {
      filetrav.createNewFile();
      System.out.println("New document with file name : file" + (listoffiles.length + 1) + ".txt created");
      FileInputStream input = new FileInputStream(file);
      FileOutputStream output = new FileOutputStream(filetrav);
      byte[] buffer = new byte[1024];
      int n;
      while ((n = input.read(buffer)) != -1) {
        output.write(buffer, 0, n);
      }
      input.close();
      output.close();
    } catch (IOException e) {
    }
    return true;
  }

  public static void search(String query) {
    String whereami = System.getProperty("user.dir");
    File folder = new File(whereami + "\\" + "documents" + "\\");
    File[] listoffiles = folder.listFiles();

    for (int i = 1; i <= listoffiles.length; i++) {
      File file = new File("documents" + "\\" + "file" + i + ".txt");
      System.out.println("Rank of file" + i + ".txt is " + rank(query, file));
    }


  }

  public static void main(String[] args) {
    String whereami = System.getProperty("user.dir");
    String searchstring = "software Product Line engineering";
    search(searchstring);

    File file = new File(whereami + "\\" + "abc.txt");
    File file2 = new File(whereami + "\\" + "documents" + "\\" + "abc.txt");
    try {
      addDocument(file);
      deleteDocument(file2);
    } catch (IOException e) {
    }
  }
}
